config/routes.rb
Rails.application.routes.draw do

  root 'todolists#index'
  
  get "login" => "sessions#new", as: "login"

  delete "logout" => "sessions#destroy", as: "logout"

  resources :sessions, only: [:new, :create, :destroy]

  resources :todolists do
    resources :todoitems
  end

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/todoitem.rb
class Todoitem < ActiveRecord::Base
  belongs_to :todolist
end

app/models/todolist.rb
class Todolist < ActiveRecord::Base
  belongs_to :user
  has_many :todoitems, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :profile, dependent: :destroy
  has_many :todolists, dependent: :destroy
  has_many :todoitems, through: :todolists, source: :todoitems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :ensure_login
  
  helper_method :logged_in?, :current_user

  private
  def ensure_login
  	redirect_to login_path unless session[:user_id]
  end

  def logged_in?
  	session[:user_id]
  end

  def current_user
  	@current_user = User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_login, only: [:new, :create]

  def new
  end

  def create
  	user=User.find_by(username: params[:user][:username])
		if user && user.authenticate(params[:user][:password])
			session[:user_id] = user.id
			return redirect_to root_path, notice: "Logged in successfully" 
		end
		flash[:errors] = 'Incorrect email or username'
		redirect_to login_path
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to login_path, notice: "Successful Logout"
  end
end

app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController
  before_action :set_todoitem , except: [:new, :create]#, only: [:show, :edit, :update, :destroy]

  # GET /todoitems
  # GET /todoitems.json
  # def index
  #   @todoitems = Todoitem.all
  # end

  # GET /todoitems/1
  # GET /todoitems/1.json
  def show
  end

  # GET /todoitems/new
  def new
    @todolist = Todolist.find(params[:todolist_id])
    @todoitem = @todolist.todoitems.new
  end

  # GET /todoitems/1/edit
  def edit
  end

  # POST /todoitems
  # POST /todoitems.json
  def create
    @todolist = Todolist.find(params[:todolist_id])
    @todoitem = @todolist.todoitems.new(todoitem_params)
    respond_to do |format|
      if @todoitem.save
        format.html { redirect_to @todolist, notice: 'Todo item was successfully created.' }
        format.json { render :show, status: :created, location: @todoitem }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todoitems/1
  # PATCH/PUT /todoitems/1.json
  def update
    respond_to do |format|
      if @todoitem.update(todoitem_params)
        format.html { redirect_to @todolist, notice: 'Todo item was successfully updated.' }
        format.json { render :show, status: :ok, location: @todoitem }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoitems/1
  # DELETE /todoitems/1.json
  def destroy
    @todoitem.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Todoitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoitem
      @todolist = Todolist.find(params[:todolist_id])
      @todoitem = @todolist.todoitems.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoitem_params
      params.require(:todoitem).permit(:title, :due_date, :description, :completed)
    end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  before_action :logged_in?

  
  def index
    #puts current_user, "*********"
    @todolists = current_user.todolists.paginate(page: params[:page], per_page: 8)
  end

  def create
    @todolist = Todolist.new(todolist_params)
    @todolist.user_id = session[:user_id]

    respond_to do |format|
      if @todolist.save
        puts "new lis"
        format.html { redirect_to todolists_path, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      #puts "******", params
      format.html { redirect_to :back, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = current_user.todolists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:list_name, :list_due_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<% if logged_in? %>
	<div style='float: right;'>
	Logged in as <%= current_user.username %> |
	<%= link_to "Logout", logout_path, method: :delete %>
	</div>
<% end %>


<%= yield %>



</body>
</html>

app/views/todoitems/_form.html.erb
<%= form_for([@todolist, @todoitem]) do |f| %>
  <% if @todoitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todoitem.errors.count, "error") %> prohibited this todoitem from being saved:</h2>

      <ul>
      <% @todoitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>
  <div class="actions">
   
    <%= f.submit %>
  </div>
<% end %>

app/views/todoitems/edit.html.erb
<h1>Editing Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Show', [@todolist, @todoitem] %> |
<%= link_to 'Back', @todolist %>

app/views/todoitems/index.html.erb
<p id="notice"><%= flash[:notice]  %></p>

<h1>Listing Todoitems</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todoitems.each do |todoitem| %>
      <tr>
        <td><%= todoitem.title %></td>
        <td><%= todoitem.due_date %></td>
        <td><%= todoitem.description %></td>
        <td><%= todoitem.completed %></td>
        <td><%= link_to 'Show', todoitem %></td>
        <td><%= link_to 'Edit', edit_todoitem_path(todoitem) %></td>
        <td><%= link_to 'Destroy', todoitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todoitem', new_todoitem_path %>

app/views/todoitems/new.html.erb
<h1>New Todo Item</h1>

<%= render 'form' %>

<%= link_to 'Back', @todolist %>

app/views/todoitems/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Title:</strong>
  <%= @todoitem.title %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @todoitem.due_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todoitem.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todoitem.completed %>
</p>

<%= link_to 'Edit', edit_todolist_todoitem_path(@todolist, @todoitem) %> |
<%= link_to 'Back', @todolist %>

app/views/todolists/_form.html.erb
<%= form_for(@todolist) do |f| %>
  <% if @todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% @todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_name %><br>
    <%= f.text_field :list_name %>
  </div>
  <div class="field">
    <%= f.label :list_due_date %><br>
    <%= f.date_select :list_due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<p id="notice"><%= flash[:notice]  %></p>

<h1>Listing Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>List name</th>
      <th>List due date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><%= todolist.list_name %></td>
        <td><%= todolist.list_due_date %></td>
        <td><%= link_to 'Show', todolist %></td>
        <td><%= link_to 'Edit', edit_todolist_path(todolist) %></td>
        <td><%= link_to 'Destroy', todolist, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @todolists %>

<br>

<%= link_to 'New Todo list', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>List name:</strong>
  <%= @todolist.list_name %>
</p>

<p>
  <strong>List due date:</strong>
  <%= @todolist.list_due_date %>
</p>

<%= link_to 'Edit', edit_todolist_path(@todolist) %> |
<%= link_to 'Back', todolists_path %>
<%= link_to 'New Todo Item', new_todolist_todoitem_path(@todolist) %>

<h1>Listing Todo Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Due date</th>
      <th>Description</th>
      <th>Completed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todolist.todoitems.each do |todoitem| %>
      <tr>
        <td><%= todoitem.title %></td>
        <td><%= todoitem.due_date %></td>
        <td><%= todoitem.description %></td>
        <td><%= todoitem.completed %></td>
        <td><%= link_to 'Show', [@todolist, todoitem] %></td>
        <td><%= link_to 'Destroy', [@todolist, todoitem], method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>